version: 3.2

services:
  snoopy:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: 5